decentralized-identity/veramo

- .circleci/config.yml
- package.json
- yarn.lock
This PR sets up the base semantic release commands and runs in dry mode which doesn't create a new npm a proper release yet
> Add semantic release job

- examples/expressjs-ethr/src/index.ts
- examples/expressjs-ethr/yarn.lock
- jest.json
- package.json
- packages/daf-cli/src/msg.ts
- packages/daf-url/src/__tests__/message-validator.test.ts
- packages/daf-url/src/message-validator.ts
- setupJest.js
- yarn.lock
> feat: Fetching URL to get the message payload

- packages/daf-selective-disclosure/src/helper.ts
Fixes query for required issuers in sdr messages
> Create identities from required issuers in sdr (fix)

- docs/Docs.md
- packages/daf-cli/src/credential.ts
- packages/daf-cli/src/setup.ts
- packages/daf-core/src/entities/credential.ts
- packages/daf-core/src/graphql/graphql-core.ts
- packages/daf-core/src/index.ts
- packages/daf-core/src/migrations/CredentialStatus1587985317000.ts
- packages/daf-core/src/migrations/index.ts
- packages/daf-w3c/package.json
- packages/daf-w3c/src/action-handler.ts
- packages/daf-w3c/src/graphql.ts
- packages/daf-w3c/src/message-handler.ts
- packages/tsconfig.json
- yarn.lock
Fixes: #129 and adds CredentialStatus to the data model
> Adding CredentialStatus to data model

- README.md
I know this is basic, but it's useful for noobs like me!
> Hyperlinking a few tools

- packages/daf-core/src/graphql/graphql-core.ts
- packages/daf-core/src/index.ts
Couple small changes so that you can access the sender while saving
> feat: pass along authentication metadata into handlers

- packages/daf-cli/default/config.js
- packages/daf-cli/package.json
- packages/daf-cli/src/config.ts
- packages/daf-cli/src/graphql.ts
- packages/daf-cli/src/setup.ts
- packages/daf-core/src/graphql/graphql-base-type-defs.ts
- packages/daf-core/src/graphql/graphql-core.ts
- packages/daf-ethr-did/src/identity-controller.ts
- packages/daf-ethr-did/src/identity-provider.ts
- packages/daf-resolver/src/resolver.ts
- yarn.lock
> feat: CLI config

- examples/rest-api/README.md
* Fix .type reference
* Move former attribute .did to new attribute .data.issuer
> Correct VC signing documentation

- packages/daf-core/src/graphql/graphql-core.ts
> fix: GraphQL orderBy

- packages/daf-core/src/entities/claim.ts
Some claims are very big so a bigger field is needed
> Big value handling

- packages/daf-ethr-did/src/identity-controller.ts
This allows a client to use it to poll for successful mining
> feat: Return the txHash in addPublic key

- packages/daf-cli/package.json
- packages/daf-core/package.json
- packages/daf-did-comm/package.json
- packages/daf-did-jwt/package.json
- packages/daf-elem-did/package.json
- packages/daf-ethr-did/package.json
- packages/daf-fs/package.json
- packages/daf-libsodium/package.json
- packages/daf-local-storage/package.json
- packages/daf-react-native-async-storage/package.json
- packages/daf-react-native-libsodium/package.json
- packages/daf-resolver-universal/package.json
- packages/daf-resolver/package.json
- packages/daf-selective-disclosure/package.json
- packages/daf-trust-graph/package.json
- packages/daf-url/package.json
- packages/daf-w3c/package.json
- packages/daf-web-did/package.json
This PR should trigger a feature release to overpass the version conflict caused by the partial `daf-contrib` repo.
> feat(release): Fix package descriptions and trigger new minor release

- packages/daf-cli/package.json
- packages/daf-core/package.json
- packages/daf-did-comm/package.json
- packages/daf-did-jwt/package.json
- packages/daf-elem-did/package.json
- packages/daf-ethr-did/package.json
- packages/daf-fs/package.json
- packages/daf-libsodium/package.json
- packages/daf-local-storage/package.json
- packages/daf-react-native-async-storage/package.json
- packages/daf-react-native-libsodium/package.json
- packages/daf-resolver-universal/package.json
- packages/daf-resolver/package.json
- packages/daf-selective-disclosure/package.json
- packages/daf-trust-graph/package.json
- packages/daf-url/package.json
- packages/daf-w3c/package.json
- packages/daf-web-did/package.json
This should overpass the 6.1.2 & 6.2 versions that were released broken/incomplete
> feat(release): Trigger a new minor release

- packages/daf-cli/package.json
- packages/daf-cli/src/server.ts
- yarn.lock
This lets any web client execute cloud agent methods
> feat: CLI server using CORS

- packages/daf-did-jwt/package.json
- packages/daf-did-jwt/src/__tests__/didkey.test.ts
- packages/daf-libsodium/package.json
- packages/daf-react-native-libsodium/package.json
- packages/daf-selective-disclosure/package.json
- yarn.lock
The underlying issue was fixed in https://github.com/decentralized-identity/did-jwt/issues/141.
This PR only updates the `did-jwt` dependency and adds a test to check how such a JWT behaves in DAF.
fixes #288
> fix(daf-did-jwt): fix EdDSA JWT verification

- packages/daf-cli/default/default.yml
- packages/daf-cli/src/did.ts
- packages/daf-ethr-did/package.json
- packages/daf-ethr-did/src/identifier-provider.ts
- yarn.lock
No unit tests. Tried it out on Rinkeby using CLI - seems to be working fine
> feat: add ethrDID removeKey, removeService

- .github/stale.yml
- renovate.json
This sets up configurations for renovate bot and stale bot
> chore: configure bots

- .github/workflows/build-test-publish-on-push.yml
- package.json
This adds an experimental channel for releases that are too early to mint into a stable API
> ci: add @experimental release channel

- __tests__/localAgent.test.ts
- __tests__/localMemoryStoreAgent.test.ts
- __tests__/restAgent.test.ts
- __tests__/shared/resolveDid.ts
- packages/cli/default/default.yml
- packages/did-provider-key/package.json
- packages/did-provider-key/src/index.ts
- packages/did-provider-key/src/resolver.ts
- yarn.lock
This uses [did-key.js](https://github.com/transmute-industries/did-key.js) from transmute-industries
fixes #352
closes #448
> feat: add native resolver for did:key

- packages/data-store/src/entities/claim.ts
- packages/data-store/src/entities/credential.ts
- packages/data-store/src/entities/identifier.ts
- packages/data-store/src/entities/key.ts
- packages/data-store/src/entities/message.ts
- packages/data-store/src/entities/presentation.ts
- packages/data-store/src/entities/service.ts
After deploying in the App & Play Stores, I got an error with the TypeORM code working with these entities.  This fixed the problem.
> add names to entities (so that code on devices succeeds)

- packages/cli/src/did.ts
> fix(cli): print entire JSON tree resulting from DID resolution

- package.json
- packages/cli/default/client.yml
- packages/cli/default/default.yml
HOTFIX: The recently added plugin methods were not usable with CLI.
This PR fixes that.
> fix(cli): export recent methods from CLI local and remote

- __tests__/shared/saveClaims.ts
- packages/core/plugin.schema.json
- packages/core/src/types/IDataStore.ts
- packages/data-store/src/data-store.ts
> feat(data-store): delete verifiable credential

- __tests__/localAgent.test.ts
- __tests__/localMemoryStoreAgent.test.ts
- __tests__/restAgent.test.ts
- __tests__/shared/didDiscovery.ts
- packages/data-store/src/data-store.ts
> fix: dataStoreDeleteVerifiableCredential

- __tests__/shared/keyManager.ts
- packages/key-manager/src/abstract-key-management-system.ts
- packages/key-manager/src/key-manager.ts
- packages/kms-local/src/key-management-system.ts
> fix: handle eth_signTransaction with from field

- packages/remote-server/src/messaging-router.ts
> feat: MessagingRouter `save` option

- packages/remote-server/package.json
- packages/remote-server/src/web-did-doc-router.ts
- yarn.lock
> feat: default services for WebDidDocRouter

- packages/remote-server/src/api-key-auth.ts
> fix(remote-server): api-key-auth

- packages/remote-server/src/web-did-doc-router.ts
Properly checking if default services are provided
> fix(remote-server): web-did-doc-router

- .vscode/launch.json
- README.md
> docs: rewrite readme and fix links

- packages/cli/src/sdr.ts
> fix: fix inquirer prompt for subject DID during SDR

- packages/core/src/types/IIdentifier.ts
- packages/remote-server/src/web-did-doc-router.ts
Issue: https://github.com/uport-project/veramo/issues/838
> Add key types: 'Bls12381G1Key2020' and 'Bls12381G2Key2020'

- packages/core/plugin.schema.json
- packages/did-comm/plugin.schema.json
* plugin schemas need to be regenerated to fix npm publish flow
> chore: Regenerate plugin schemas

- packages/core/plugin.schema.json
- packages/data-store-json/src/data-store-json.ts
> fix(data-store-json): structuredClone

- packages/cli/src/credential.ts
Adding choices when select Subject DID instead of always default it to the first identifier. 
This PR fix issues mentioned in #897
> Add choices when selecting credential Subject in CLI

- packages/credential-w3c/src/action-handler.ts
> fix(credential-w3c): manually merging schemas

- AWESOME.md
- README.md
This is bootstrapping a list of projects that are using or extending Veramo.
Please follow the spirit of this PR and add more or suggest improvements!
> docs(awesome): initial commit of the awesome list of awesome projects

- AWESOME.md
add a link to the VC revocation plugin from Spherity to the awesome list
> docs(awesome): add Spherity VC status plugin

- AWESOME.md
Example:
`closes #123`
`fixes #456`
Linking to an issue provides some context and a reason for the PR to be reviewed, as well as simplifying the release
notes and changelogs that get generated automatically. If an issue is linked like this it will be automatically closed
when the PR is merged.
A clear description of what this PR brings.
> Update AWESOME.md adding ID Pocket

- packages/core/src/plugin.schema.json
- packages/did-comm/src/plugin.schema.json
- yarn.lock
Example:
Unstable branch wasn't published after last PR due to yarn.lock and plugin.schema.json mismatch
> fix: update yarn.lock and plugin schemas

- Dockerfile
The dockerfile we had in the root dir is creating confusion and should be removed.
> chore: remove experimental dockerfile

- packages/utils/src/did-utils.ts
cleanup to reduce duplicate code
> refactor(utils): eliminate duplicated code in extractPublicKeyHex

- packages/credential-ld/package.json
- yarn.lock
Upgrade digitalcredentials/vc to 5.0.0 
Notable Changes: https://github.com/digitalcredentials/vc/pull/9
> chore: update digitalcredentials/vc to 5.0.0

- packages/remote-server/src/agent-router.ts
- packages/remote-server/src/messaging-router.ts
> feat: increase request limit for routers

- packages/did-comm/src/protocols/index.ts
Recent DIDComm Mediator work was missing 1 export
> fix: correctly export PickupMediatorMessageHandler

- packages/did-comm/src/protocols/index.ts
Recent DIDComm Mediator work was actually missing 2 exports :)
> fix: correctly export PickupRecipientMessageHandler

- packages/cli/default/default.yml
- packages/cli/package.json
- pnpm-lock.yaml
Added resolver for `did:3` identifiers to the default `cli` config
> feat(cli): added did:3 resolver

- packages/cli/src/server.ts
- packages/test-react-app/package.json
- pnpm-lock.yaml
> fix(cli): server await getConfig

- packages/core-types/src/plugin.schema.json
- packages/did-comm/src/plugin.schema.json
> fix: plugin schemas

- AWESOME.md
fixes #1279
Updated some of the entries in the AWESOME list
> docs: update AWESOME list

- packages/did-provider-pkh/README.md
fix title in packages/did-provider-pkh/README.md .
`did:web` -> `did:pkh`
> fix did:pkh provider name in README.md

- packages/did-comm/README.md
fix to fit the markdown table syntax.
Before
> fix to fit the markdown table syntax.

- packages/utils/src/jwk-did-utils.ts
Fixes #1324
Exports createJWK function from utils package
> [proposal] export createJWK

- packages/core-types/src/types/ICredentialIssuer.ts
closes #1356
`packages/core-types/src/types/ICredentialIssuer.ts` is updated with correct description for type definition
> docs: update 'packages/core-types/src/types/ICredentialIssuer.ts'

- packages/core-types/src/plugin.schema.ts
core plugin schema needed to be rebuilt for npm publish
> chore: update plugin schema

- packages/core-types/src/plugin.schema.ts
Last commit did not push a release due to mismatch between committed schema and schema after build
* ran `pnpm build`
* committed results
> fix(core-types): regenerate schema

- packages/test-react-app/jest-puppeteer.config.cjs
* fix broken browser tests
* puppeteer config 
> fix: fix jest puppeteer config
