decentralized-identity/veramo

packages/daf-cli/src/graphql.ts
packages/daf-trust-graph/src/graphql.ts
packages/daf-trust-graph/src/index.ts
packages/daf-w3c/src/graphql.ts

Here are queries that I was using to test this:
```graphql
mutation sign {
actionSignVc(
did: "did:ethr:0x2296f523a23d9813501b51b86f99227d4f55ff1f",
data:{
sub: "did:ethr:0xe6ab9e10aee1f9571901f758bb82e9ba3a41b64f",
vc: {
context: ["https://www.w3.org/2018/credentials/v1"],
type: ["VerifiableCredential"],
credentialSubject: {
name: "Simonas"
}
}
}
)
}
mutation send {
actionSendJwt (
from: "did:ethr:0x2296f523a23d9813501b51b86f99227d4f55ff1f",
to: "did:ethr:0xe6ab9e10aee1f9571901f758bb82e9ba3a41b64f",
jwt: "eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NkstUiJ9.eyJpYXQiOjE1NzQ2ODY4NjAsInN1YiI6ImRpZDpldGhyOjB4ZTZhYjllMTBhZWUxZjk1NzE5MDFmNzU4YmI4MmU5YmEzYTQxYjY0ZiIsInZjIjp7InR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiXSwiQGNvbnRleHQiOlsiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiXSwiY3JlZGVudGlhbFN1Ymp …
```

feat: Added actionSignVc mutation

---

packages/daf-cli/src/credential.ts
packages/daf-cli/src/sdr.ts

Hey Simonas,
it would be helpful if `daf-cli` would be able to print the raw jwt if the qr-code was NOT requested for SDR and Credentials module.
Here's a small PR for that.

feat: print raw JWT if no QR-Code output is requested.

---

docs/Docs.md

Primarily addresses references to CoreGql that should be either Gql or Gql.Core

Minor fixes to graphql server documentation

---

packages/daf-did-jwt/package.json
packages/daf-libsodium/package.json
packages/daf-react-native-libsodium/package.json
packages/daf-selective-disclosure/package.json
packages/daf-trust-graph/package.json
yarn.lock

After this change, there is no longer any need to use ES256K-R from DAF
bump did-jwt
* daf-did-jwt: 4.2.0
* daf-libsodium: ^4.0.0 → 4.2.0
* daf-react-native-libsodium: ^4.0.0 → 4.2.0
* daf-selective-disclosure: ^4.0.0 → 4.2.0
* daf-trust-graph: ^4.0.0 → 4.2.0

fix(deps): enable verification of ES256K signatures with default did:ethr: docs

---

packages/daf-core/src/__tests__/resolvers.test.ts
packages/daf-core/src/graphql/graphql-core.ts

Still need to add more tests.  Allows configuring agent with authentication boolean at instantiation.  An auth-identity can be set in the request context and resolvers will include that identity in their generated queries if authentication is set to true.

feat: Optionally add permissions to gql resolvers

---

examples/rest-api/index.ts

Without the type declaration the example wouldn't start with ts-node 8.6.2.

Add type declaration

---

examples/rest-api/README.md

I ran into the issue that the application wouldn't start without this step. Since there's no build target in package.json this solution seems to be the easiest possible fix of the documentation.

Add build step before starting the application

---

packages/daf-resolver/src/resolver.ts

When passing in a custom network list to the DafResolver (e.g. consortium network) it will fall back to the mainner registry address in https://github.com/decentralized-identity/ethr-did-resolver/blob/develop/src/ethr-did-resolver.js#L187
This type change allows a DAF Agent to pass in the registry address for the network in question.
I specifically did not change the networks list because it would force people that use a non infure main/testnet node to configure the address, or force you to maintain a second list of addresses from the networks.json in ethr-did-resolver package.
Do note that this networks list was removed in v2 of ethr-did-resolver so this list would need ot be adjusted anyway when upgrading.

fix: allow to pass in a custom registry address

---

.gitignore
packages/daf-ethr-did/src/identity-provider.ts
packages/daf-resolver/package.json
yarn.lock

The network configuration that is used for identity-provider did not get propagated entirely down to the identity-controller for the daf-ethr-did package; this PR fixes that.
Also, I updated the version of ethr-did-resolver being used in daf

fix: ethr resolver for private nets

---

packages/daf-cli/src/version.ts

/**
* Set the program version to `str`.
*
* This method auto-registers the "-V, --version" flag
* which will print the version number when passed.
*
* @param {string} str
* @param {string} [flags]
* @returns {Command} for chaining
*/
version(str: string, flags?: string): Command;

fix: Version takes only two parameters

---

packages/daf-url/src/message-handler.ts

I was sending through a message with a JWT in the raw and my agent running in the browser has in the MessageHandler chain `daf-url` active. 
I ran into errors because `const parsed = parse(message.raw, true)` returned an URL object with the URL of the page. The URL came out as http://localhost:3000/jwthere. Which of course did not resolve to something daf could understand.
After some digging, I found the following in the `url-parse` documentation
> Note that when `url-parse` is used in a browser environment, it will default to
using the browser's current window location as the base URL when parsing all
inputs. To parse an input independently of the browser's current URL (e.g. for
functionality parity with the library in a Node environment), pass an empty
location object as the second …

fix: handle jwt messages correctly in daf-url in browser environments

---

packages/daf-selective-disclosure/src/graphql.ts
packages/daf-w3c/src/graphql.ts

I'm sharing my daf graphql config across some repo's and i want to prepare it, and export it to be used where needed.
When doing the following:
```
export const dafResolvers = merge(
Daf.Gql.Core.resolvers,
Daf.Gql.IdentityManager.resolvers,
W3cGql.resolvers
SdrGql.resolvers
);
```
Typescript conplains that it cannot send along Context
```
Exported variable 'xxx' has or is using name 'Context' from external module "./node_modules/daf-selective-disclosure/build/graphql" but cannot be named.
```
In daf-core it is exported so i added the missing exports in both packages

fix: export context from daf-selective-disclosure and daf-w3c

---

__tests__/shared/handleSdrMessage.ts
packages/daf-selective-disclosure/src/action-handler.ts

fixes error: `{"error":"syntax error at or near \")\""}`
This prevents from checking the db if `issuers` is empty. (The message sdr payload has an empty issuers array if no issuers are provided)

Allow empty issuers in sdr credential request

---

examples/react-app/src/App.tsx
examples/react-app/yarn.lock
packages/daf-resolver/package.json
yarn.lock

[`daf/examples/react-app`](https://github.com/uport-project/daf/tree/master/examples/react-app) cannot work due to type error and CORS's error
- Writing code of an old type for `IdentityManager#getIdentityProviders` caused a type error
- CORS's error is caused by [decentralized-identity/web-did-resolver](https://github.com/decentralized-identity/web-did-resolver)
- Type error was fixed in https://github.com/uport-project/daf/commit/077580a3c744d3ef8b2f13b76daa3fcba802e995
- https://github.com/decentralized-identity/web-did-resolver/pull/88  has fixed the CORS error. So I updated the package version

Fix a bug that prevented react-app from working.

---

packages/daf-react-native-libsodium/src/key-management-system.ts

#228 
Feature branch to support **import Identity** for daf-react-native-libsodium package

Import DID support for daf-react-native-libsodium

---

packages/daf-did-comm/src/action-handler.ts

Allow to set headers to the HTTPS POST request when using DID Comm action handler

feat: Enable setting headers to DAF DID Comm

---

packages/daf-cli/default/default.yml

Calling `daf create-config` will generate an `agent.yml` file with `schemaValidation` set to `false`.
This makes it a bit easier to work through issues with inconsistent responses from some plugins.
This will also match the default for the `agent`.

fix: Disable schemaValidation in CLI default config

---

__tests__/restAgent.test.ts
packages/daf-cli/src/server.ts
packages/daf-cli/views/home.html
packages/daf-express/api/daf-express.api.md
packages/daf-express/src/agent-router.ts
packages/daf-express/src/api-schema-router.ts
packages/daf-express/src/did-doc-router.ts
packages/daf-express/src/index.ts
packages/daf-express/src/web-did-doc-router.ts

```typescript
import express from 'express'
import { agent } from './agent'
import { AgentRouter, ApiSchemaRouter, DidDocRouter } from 'daf-express'
const getAgentForRequest = async (req: express.Request) => agent
const exposedMethods = agent.availableMethods()
const basePath = '/agent'
const schemaPath = '/open-api.json'
const agentRouter = AgentRouter({
getAgentForRequest,
exposedMethods,
})
const schemaRouter = ApiSchemaRouter({
basePath,
getAgentForRequest,
exposedMethods,
})
const didDocRouter = DidDocRouter({
getAgentForRequest
})
const app = express()
app.use(basePath, agentRouter)
app.use(schemaPath, schemaRouter)
app.use(didDocRouter)
app.listen(3002)
```
```typescript
// 'did:web:example.com'
const serverIdentity = await agent.identityManagerCreateIdentity({
alias: …
```

Web DID path (multi user) support 

---

packages/daf-core/package.json
packages/daf-core/plugin.schema.json
packages/daf-did-jwt/package.json
packages/daf-did-jwt/src/__tests__/didkey.test.ts
packages/daf-did-jwt/src/message-handler.ts
packages/daf-libsodium/package.json
packages/daf-react-native-libsodium/package.json
packages/daf-resolver-universal/package.json
packages/daf-resolver/package.json
packages/daf-selective-disclosure/package.json
packages/daf-w3c/package.json
packages/tsconfig.settings.json
yarn.lock

`JwtMessageHandler` can parse them but they fail later in the the message handler chain if `typ` is missing.
Also, this fixes #291

fix(daf-did-jwt): Fix parsing of JWT with missing `typ` in header

---

packages/daf-resolver/package.json
packages/daf-resolver/src/__tests__/integration.test.ts
packages/daf-resolver/src/__tests__/resolver.test.ts
packages/daf-resolver/src/universal-resolver.ts
yarn.lock

This fixes #302
Also add integration tests for the daf-resolver package

fix(daf-resolver): import cross-fetch in universal-resolver.ts

---

__tests__/shared/verifiableData.ts
packages/daf-w3c/api/daf-w3c.api.md
packages/daf-w3c/src/action-handler.ts
packages/daf-w3c/src/index.ts

This was branched of rename branch. Only the last commit matters here

feat: Simpler create VC/VP

---

.github/workflows/run-tests.yml

this saves a few seconds on CI by using the cache more often

chore(ci): relax cache-key requirements for CI

---

__tests__/localAgent.test.ts
__tests__/restAgent.test.ts

We need to import from `/src` in integration tests, so that they are included in coverage report

chore: include integration tests in coverage

---

__tests__/restAgent.test.ts
packages/cli/default/client.yml
packages/cli/default/default.yml
packages/cli/src/lib/objectCreator.ts
packages/cli/src/server.ts
packages/cli/src/setup.ts
packages/remote-server/package.json
packages/remote-server/src/agent-router.ts
packages/remote-server/src/api-key-auth.ts
packages/remote-server/src/api-schema-router.ts
packages/remote-server/src/default-did.ts
packages/remote-server/src/get-agent-for-request.ts
packages/remote-server/src/index.ts
packages/remote-server/src/messaging-router.ts
packages/remote-server/src/request-agent-router.ts
packages/remote-server/src/web-did-doc-router.ts

#374
```yml
version: 2.0
constants:
baseUrl: http://localhost:3332
port: 3332
secretKey: 29739248cad1bd1a0fc4d9b75cd4d2990de535baf5caadfdf8d8f86664aa830c
databaseFile: ./database.sqlite
methods:
- keyManagerGetKeyManagementSystems
- keyManagerCreate
- keyManagerGet
- keyManagerDelete
- keyManagerImport
- keyManagerEncryptJWE
- keyManagerDecryptJWE
- keyManagerSignJWT
- keyManagerSignEthTX
- didManagerGetProviders
- didManagerFind
- didManagerGet
- didManagerCreate
- didManagerGetOrCreate
- didManagerImport
- didManagerDelete
- didManagerAddKey
- didManagerRemoveKey
- didManagerAddService
- didManagerRemoveService
- resolveDid
- dataStoreGetMessage
- dataStoreSaveMessage
- dataStoreGetVerifiableCredential
- dataStoreSaveVerifiableCredential
- dataStoreGetVerifiablePresentation
- …
```

refactor(cli): use routers defined in config

---

packages/remote-server/src/web-did-doc-router.ts

fix: use URI encoded host in web-did-doc-router

---

__tests__/shared/verifiableData.ts
packages/credential-w3c/src/action-handler.ts

During JSON <-> JWT transformation the fields that are mentioned in the [vc-data-model encoding](https://www.w3.org/TR/vc-data-model/#jwt-encoding) are removed by default.
This PR adds the option to keep the JSON fields in the JWT payload when creating verifiable credentials & presentations.
To keep the respective fields (effectively duplicating the data they contain) one can set the `removeOriginalFields` option to `false`:
Examples:
```typescript
const verifiableCredential = await agent.createVerifiableCredential({
credential: {
issuer: { id: identifier.did },
credentialSubject: {
id: 'did:web:example.com',
you: 'Rock',
},
},
proofFormat: 'jwt',
removeOriginalFields: false,
})
```
```typescript
const verifiablePresentation = await agent.createVerifiablePresentation({
presentation: {
// …
```

feat: add option to keep payload fields when creating JWT VC/VP

---

packages/cli/src/dev.ts
packages/credential-w3c/plugin.schema.json

`veramo dev generate-plugin-schema` was failing because of the transmute typescript bug (https://github.com/transmute-industries/vc.js/issues/60)
This ignores the errors thrown because of it (which don't really affect the API/plugin schema results) and rebuilds the plugin schema.
For testing, I ran `veramo server` and then browsed to http://localhost:3332/api-docs/ where the new methods appear without error

fix: fix plugin schema generator for broken ts plugins

---

package.json

This is an attempt to fix `lerna ERR! E400 Must associate a single dist tag with new publishes.` that [we got on `main`](https://github.com/uport-project/veramo/runs/2438794873?check_suite_focus=true#step:14:126).

fix(ci): explicitly publish to `@latest` from `main` branch

---

packages/credential-w3c/src/__tests__/action-handler.test.ts
packages/credential-w3c/src/__tests__/message-handler.test.ts
packages/credential-w3c/src/action-handler.ts

Fixes #516; fixed missing handling of Ed25519 keys when creating VPs

Fixes #516; fixed missing handling of Ed25519 keys when creating VPs

---

.vscode/settings.json
__tests__/shared/keyManager.ts
__tests__/shared/verifiableData.ts
packages/cli/default/default.yml
packages/core/plugin.schema.json
packages/core/src/types/IIdentifier.ts
packages/core/src/types/IKeyManager.ts
packages/credential-w3c/src/__tests__/action-handler.test.ts
packages/credential-w3c/src/action-handler.ts
packages/data-store/plugin.schema.json
packages/data-store/src/entities/key.ts
packages/data-store/src/identifier/did-store.ts
packages/did-comm/plugin.schema.json
packages/did-provider-ethr/package.json
packages/did-provider-ethr/src/ethr-did-provider.ts
packages/did-provider-ethr/src/kms-eth-signer.ts
packages/did-resolver/src/__tests__/integration.test.ts
packages/key-manager/src/abstract-key-management-system.ts
packages/key-manager/src/key-manager.ts
packages/kms-local-react-native/package.json
packages/kms-local-react-native/src/key-management-system.ts
packages/kms-local/package.json
packages/kms-local/src/key-management-system.ts
packages/selective-disclosure/plugin.schema.json
packages/selective-disclosure/src/action-handler.ts
yarn.lock

This PR extends the signing capabilities of the `key-manager` plugin.
The `key-manager` plugin now exposes a `keyManagerSign` method that accepts extra `alg`, `enc` parameters and supports extension of the parameter object.
The `enc` parameter indicates the encoding of the `data` string, defaulting to `utf-8` if absent.
The `alg` option should indicate an algorithm to be used.
Depending on the capabilities of the KMS (one of the `AbstractKeyManagementSystem` implementations), different signatures can be requested.
For example:
* a KMS implementation that has direct access to key material for a `Secp256k1` key should be able to support:
* `ES256K`, `ES256K-R`, `eth_signTransaction`, `eth_signTypedData`, `eth_signMessage`
* a KMS implementation that is based on a `web3` abstraction, would …

feat(key-manager): add generic signing capabilities

---

packages/kms-local/package.json
packages/kms-local/src/key-management-system.ts
yarn.lock

fixes #549
Since #529 got merged, secp256k1 key generation is very slow on react-native (tested on android).
The culprit seems to be the `pbkdf2` method that gets called by `@ethersproject/wallet#Wallet.createRandom()`
This fix instantiates a `SigningKey` directly instead of deriving from a mnemonic, therefore sidestepping the call to pbkdf2

fix: speed up secp256k1 keygen

---

__tests__/shared/keyManager.ts
packages/core/plugin.schema.json
packages/core/src/types/IKeyManager.ts
packages/key-manager/src/__tests__/default.test.ts
packages/key-manager/src/abstract-key-management-system.ts
packages/key-manager/src/key-manager.ts
packages/kms-local/src/__tests__/kms-local.test.ts
packages/kms-local/src/key-management-system.ts

* `key-manager` plugin exposes a new method that computes a shared key (Diffie Hellman) between a secret key the agent manages and a public key of another party, returning a promise that resolves to the hex encoding string of the shared key.
```ts
async keyManagerSharedKey({secretKeyRef: string, publicKey: {type: string, publicKeyHex: string}}): Promise<string>`
```
The result is the RAW shared secret (scalar multiplication in the case of ECC).
To use this for symmetric encryption, one would need to hash it to arrive at a shared Symmetric Key
* To do this, there is a new requirement of the `AbstractKeyManagementSystem` class for a new abstract method `sharedKey()`
* The `kms-local` package implements this new `sharedKey` method
* `kms-local` supports `Ed25519` & `X25519` keys for …

feat(key-manager): add method to compute a shared secret

---

packages/core/src/types/IKeyManager.ts
packages/key-manager/src/abstract-key-management-system.ts
packages/key-manager/src/key-manager.ts
packages/kms-local/src/key-management-system.ts

The KMS is only used to compute shared secret, it doesn't need to deal with JWE directly.
This PR moves the responsibility of createJWE and decryptJWE to the `key-manager` layer which eventually uses the `shared secret` functionality of the KMS to perform the same task.
fixes #556

feat(key-manager): implement JWE functionality directly in `key-manager`

---

packages/selective-disclosure/src/message-handler.ts

Added optional chaining to the first if statement so that if message.data doesn't exist, the program doesn't fail.

Fixes #560, don't assume that message.data exists

---

__tests__/shared/handleSdrMessage.ts
packages/cli/src/sdr.ts
packages/selective-disclosure/plugin.schema.json
packages/selective-disclosure/src/__tests__/validate-presentation.test.ts
packages/selective-disclosure/src/action-handler.ts
packages/selective-disclosure/src/types.ts

BREAKING CHANGE:
`getVerifiableCredentialsForSdr` and `validatePresentationAgainstSdr`
now returns `UniqueVerifiableCredential ` (`{ hash: string, verifiableCredential: VerifiableCredential }`)
instead of `VerifiableCredential`
Fixes: #496

feat(sdr): returns UniqueVerifiableCredential

---

__tests__/localAgent.test.ts
__tests__/localMemoryStoreAgent.test.ts
__tests__/restAgent.test.ts
__tests__/shared/didManager.ts
__tests__/shared/didcomm.ts
__tests__/shared/resolveDid.ts
__tests__/utils/fake-did.ts
packages/did-comm/src/action-handler.ts
packages/did-comm/src/utils.ts
packages/did-provider-key/src/resolver.ts
yarn.lock

I added this `did:fake` method to the integration test utilities.
This fake DID is resolved using the local agent database.
This PR also contains a fix for a bug in did-comm packing where some keys were getting converted twice from Ed25519 public to X25519 public, generating invalid packed messages.

feat: add fake did method usable in tests

---

__tests__/localAgent.test.ts
__tests__/localMemoryStoreAgent.test.ts
__tests__/restAgent.test.ts
package.json
packages/cli/default/default.yml
packages/cli/package.json
packages/core/plugin.schema.json
packages/core/src/types/IResolver.ts
packages/did-provider-key/package.json
packages/did-provider-key/src/resolver.ts
packages/did-resolver/src/resolver.ts
yarn.lock

This PR contains some small fixes to align the APIs before the release:
* exporting the recently added agent methods to the CLI server default
* bumping dependencies
* requesting LD DIDDocument by default (works with the latest did-key.js resolver)
* reformatting the code

cleanup before release

---

packages/did-comm/src/utils.ts
packages/did-provider-web/src/web-did-provider.ts
packages/remote-server/src/default-did.ts
packages/remote-server/src/web-did-doc-router.ts

fixes #618
Also contained in this PR:
* a fix for a potential bug in did-comm message unpacking when filtering local keys
* express `DIDCommMessaging` service for the default did:web document in `@veramo/remote-server`
* add an `Ed25519` key to the default did:web document in `@veramo/remote-server`
This makes the default did:web managed by the `@veramo/remote-server` DIDComm v2 capable

feat(remote-server): express did:web verification relationships in DIDDocument

---

__tests__/localAgent.test.ts
__tests__/localMemoryStoreAgent.test.ts
__tests__/restAgent.test.ts
__tests__/shared/didDiscovery.ts
__tests__/shared/didManager.ts
__tests__/shared/keyManager.ts
__tests__/shared/resolveDid.ts
__tests__/shared/verifiableData.ts
packages/did-provider-ethr/src/ethr-did-provider.ts

This allows numbers to be used for the `network` parameter of `EthrDidProvider`.
```
'did:ethr:421611': new EthrDIDProvider({
network: 421611,
// ...
}),
```
This is a small workaround until EthrDidControler API can be improved to accept more flexible configuration.
fixes #677
I also rearranged some of the imports in the integration tests for easier development.

fix(did-ethr-provider): allow initialization with chainId number

---

packages/did-comm/src/types/IDIDComm.ts
packages/did-comm/src/types/message-types.ts

The API docs website generator is broken because of this.

docs(did-comm): fix some inline documentation for DIDComm

---

packages/did-comm/plugin.schema.json

* Generating schema on Windows machine added extra escaped character. Regenerated on unix to remove.

chore: Regenerate did-comm plugin schema

---

packages/credential-ld/src/ld-credential-module.ts
packages/credential-status/LICENSE
packages/credential-status/README.md
packages/credential-status/api-extractor.json
packages/credential-status/jest.config.js
packages/credential-status/package.json
packages/credential-status/plugin.schema.json
packages/credential-status/src/__tests__/credential-status.test.ts
packages/credential-status/src/credential-status.ts
packages/credential-status/src/index.ts
packages/credential-status/src/types.ts
packages/credential-status/tsconfig.json
packages/tsconfig.json
yarn.lock

Hi folks. This is our another (first one was [here](https://github.com/uport-project/veramo/pull/814)) try of implementing support for the [`credentialStatus` field](https://www.w3.org/TR/vc-data-model/#status) of W3C credentials.
In fact, it's quite simple - just wrapping the [`credential-status`](https://github.com/uport-project/credential-status) library.
Any feedback is welcome and appreciated.

Credential status plugin for Veramo

---

packages/data-store-json/src/identifier/did-store.ts
packages/data-store-json/src/identifier/key-store.ts
packages/data-store-json/src/identifier/private-key-store.ts

Relates to https://github.com/uport-project/veramo/issues/857

fix(data-store-json): structuredClone

---

packages/credential-w3c/src/action-handler.ts

Added missing domain and challenge args to the createVerifiablePresentationJwt function.  This fixes an issue where creating a VP using the domain and challenge arguments would return VP with JWT with `aud: []` and without nonce field.

fix(credential-w3c): added domain and challenge args to createVerifiablePresentationJwt

---

__tests__/shared/didCommPacking.ts
packages/did-comm/plugin.schema.json
packages/did-comm/src/didcomm.ts
packages/did-comm/src/types/IDIDComm.ts
packages/did-comm/src/types/message-types.ts

**Problem:** We want to create a JWE for multiple recipients (ie.: different DID docs), by means of including these as recipients as well. Currently the JWE's recipients are only coming from the beneficiary's DID doc (keyAgreements).
**Proposal:** Extending the DIDCommMessage with a `bcc` field (~blind carbon copy) which is an array of additional beneficiary DIDs. Our proposed code resolves these into DIDdocs, and adds their keyAgreements into the recipients as well.
We don't care about sending DIDComm messages to the `bcc` recipients right now, but anyone can extend this logic in the future if so desired.
---
**Testing:** Proper unit test(s) can be added if necessary. But here's a POC test script for our use case:
```ts
import { IIdentifier } from "../../veramo/packages/core/build"; …
```

feat: Create DIDComm JWE with multiple recipients

---

packages/remote-server/src/web-did-doc-router.ts

This resolves an error caused by trying to dereference an undefined object (`options`) during resolution of locally managed `did:web`

fix(remote-server): fix error when resolving local did:web

---

packages/core/src/types/IIdentifier.ts

This hotfix is meant to ease the automatic documentation generation flow, where one of the tools fails to interpret the original syntax.
There is no functional or semantic difference.

chore(docs): use Array<T> instead of T[] to satisfy auto-docs tooling

---

packages/cli/package.json
packages/data-store/package.json
yarn.lock

This hotfix should enable building on Apple M1 chips, which was broken before sqlite3@5.0.3

fix(deps): bump sqlite3 to 5.0.8

---

packages/cli/default/default.yml

BREAKING CHANGE: `ProfileDiscoveryProvider` has been renamed to `DataStoreDiscoveryProvider` in #597. Please update your config accordingly

fix(cli): update default CLI config to account for renamed class

---

__tests__/localAgent.test.ts
__tests__/shared/web3.ts
__tests__/utils/ethers-provider.ts
packages/kms-web3/src/web3-key-management-system.ts
packages/utils/src/did-utils.ts

fix(kms-web3): use ethers _signTypedData

---

packages/credential-ld/package.json
packages/credential-ld/src/ld-default-contexts.ts
packages/credential-ld/src/module-types/jsonld/index.d.ts
packages/credential-ld/src/suites/EcdsaSecp256k1RecoverySignature2020.ts
packages/did-provider-key/package.json
yarn.lock

The fork uses `@digitalcredentials` variants of the JSON-LD libraries and upgrades some other sub-dependencies to more maintained variants.
The `@digitalcredentials` forks are more friendly for react/react-native environments.
closes #952

fix(deps): replace @transmute/lds-ecdsa-secp256k1-recovery2020 with fork

---

.gitignore
packages/core/package.json
packages/credential-status/package.json
packages/credential-w3c/package.json
packages/did-comm/package.json
packages/did-jwt/package.json
packages/key-manager/package.json
packages/kms-local/package.json
packages/selective-disclosure/package.json
packages/utils/package.json
yarn.lock

Following respective released PRs ( [`did-jwt`](https://github.com/decentralized-identity/did-jwt/pull/235) & [`did-jwt-vc`](https://github.com/decentralized-identity/did-jwt-vc/pull/115)) .
Targets only direct Veramo packages.

fix(deps): Bump `did-jwt`, `did-jwt-vc` as direct package deps

---

.github/PULL_REQUEST_TEMPLATE/bugfix.md

This adds a Github PR template.
Hopefully, if all these steps are taken before a PR is opened, we will have an easier time reviewing and accepting contributions.
Does the template make sense?

chore(ci): add PR template

---

packages/did-provider-key/src/key-did-provider.ts

`addKey` error message is currently incorrect.

Fix typo in error message for `addKey`

---

.github/pull_request_template.md
__tests__/initial.migration.test.ts
__tests__/localAgent.test.ts
__tests__/localJsonStoreAgent.test.ts
__tests__/localMemoryStoreAgent.test.ts
__tests__/restAgent.test.ts
__tests__/shared/didManager.ts
packages/credential-ld/src/__tests__/issue-verify-flow.test.ts
packages/did-manager/src/abstract-identifier-provider.ts
packages/did-manager/src/id-manager.ts
packages/did-provider-ethr/src/ethr-did-provider.ts
packages/test-react-app/src/veramo/setup.ts

fixes #968
fixes #893 - adding a network config that mentions the `name: 'rsk:testnet'` as well as the `chainId: 31` will create properly resolvable DIDs.
This PR adds the ability to use multiple networks with a single `EthrDIDProvider`. This brings us closer to having and reusing known ERC1056 deployments so that network names and chainIDs can be aligned for the public networks. Also, this will make it possible to reuse the same configuration from `ethr-did-resolver`, which would reduce the configuration boilerplate significantly.

feat(did-provider-ethr): use multiple networks per EthrDIDProvider

---

packages/kms-web3/src/web3-key-management-system.ts

feat(kms-web3): listKeys

---

packages/cli/src/credential.ts
packages/cli/src/explore/credentials.ts
packages/cli/src/explore/managed-identifiers.ts
packages/cli/src/explore/presentations.ts
packages/cli/src/explore/utils.ts
packages/cli/src/presentation.ts

Part of the motivation for this is that I could not copy-and-paste with my mouse on the content (which is frustrating... to be able to see it and not copy it!).
Even if I could use my mouse, I figure a quicker way is always helpful. :-)

feat(cli): in explore, allow copy to clipboard the text of identifier or credential or presentation

---

packages/core/plugin.schema.json
packages/core/src/types/IMessageHandler.ts
packages/credential-w3c/plugin.schema.json
packages/credential-w3c/src/action-handler.ts

closes #966
The message handler and the credential issuer plugin methods contain a `save` parameter that is used to automatically save messages, credentials and presentations to the `IDataStore` implementation.
BUT, this means that there is very tight coupling between those plugins and the data storage layer, which is very problematic for light-weight agents that don't need storage.
Marking this parameter as `@deprecated` and providing instructions on how to avoid it will allow us to remove it in the v5 release or later with plenty of time for users to adapt.
The rest of the changes are related to code formatting and adjustments of the inline docs.

fix: deprecate the `save` parameter

---

__tests__/localAgent.test.ts
packages/did-resolver/package.json
packages/did-resolver/src/__tests__/integration.test.ts
packages/did-resolver/src/resolver.ts
packages/did-resolver/tsconfig.json

fixes #976
The `DIDResolverPlugin` now accepts a map of `DIDResolver` implementations as well, to simplify user required dependencies, config, and constructor.
If a `resolver` argument is provided, it will get used instead of the mapping to ensure backward compatibility and allow users to make extra configuration.
```ts
import { Resolver } from 'did-resolver'
new DIDResolverPlugin({
resolver: new Resolver({
...ethrResolver(),
...keyResolver(),
...ionResolver()
})
})
```
```ts
new DIDResolverPlugin({
...ethrResolver(),
...keyResolver(),
...ionResolver()
})
```

feat(did-resolver): simplify DIDResolverPlugin constructor

---

__tests__/shared/credentialStatus.ts
__tests__/shared/verifiableDataJWT.ts
__tests__/shared/verifiableDataLD.ts
packages/cli/src/credential.ts
packages/core/package.json
packages/core/plugin.schema.json
packages/core/src/types/IIdentifier.ts
packages/credential-eip712/src/agent/CredentialEIP712.ts
packages/credential-ld/plugin.schema.json
packages/credential-ld/src/__tests__/issue-verify-flow.test.ts
packages/credential-ld/src/action-handler.ts
packages/credential-ld/src/ld-credential-module.ts
packages/credential-ld/src/types.ts
packages/credential-status/package.json
packages/credential-w3c/package.json
packages/credential-w3c/plugin.schema.json
packages/credential-w3c/src/action-handler.ts
packages/credential-w3c/src/message-handler.ts
packages/did-comm/package.json
packages/did-jwt/package.json
packages/did-jwt/src/message-handler.ts
packages/did-provider-ethr/package.json
packages/did-provider-ethr/src/ethr-did-provider.ts
packages/did-resolver/src/resolver.ts
packages/key-manager/package.json
packages/kms-local/package.json
packages/selective-disclosure/package.json
packages/utils/package.json
yarn.lock

fixes #935
fixes #954
fixes #375
fixes #989
* Verification override policies are now defined for Credentials as well, and, where possible, applied to JSON-LD VC/VP too (see #935).
* Verification of credentials and presentations results in an object with a `verified` boolean property and an optional `error` object with a `message` and `errorCode`. Other properties can be added by the lower level libraries performing the verification (see #954).
* `verify*()` methods still throw errors, but only in case of exceptional situations, when the agent config does not support that kind of verification or when there is a problem with the arguments.
* I'm still not sure if this is the right approach or if we should be catching these and creating response objects with error messages. **Please share …

feat(credential-w3c): align verification API between formats

---

.github/workflows/build-test-publish-on-push.yml

This should authorize the build script to auto-release from `main`

fix(ci): add GH_TOKEN for checkout and auto-release

---

CHANGELOG.md
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/credential-w3c/CHANGELOG.md
packages/credential-w3c/package.json
packages/data-store/package.json
packages/selective-disclosure/CHANGELOG.md
packages/selective-disclosure/package.json
packages/test-react-app/CHANGELOG.md
packages/test-react-app/package.json
yarn.lock

fixes #1013
The typeorm version in use was fixed to 0.3.6, disallowing user controlled upgrades to other compatible versions.
This PR bumps typeorm to 0.3.10 and uses a compatibility version range (^0.3.10)

fix(data-store): use looser typeorm version range to fix #1013

---

package.json

The prettier command used single punctuation marks ('), meaning globbing will not work, so replacing them with escaped double quotes (\") within the command solves the issue

fix: prettier command didn't work anymore (globbing issue)

---

package.json
packages/cli/package.json
packages/core/package.json
packages/credential-eip712/package.json
packages/credential-ld/package.json
packages/credential-status/package.json
packages/credential-w3c/package.json
packages/data-store-json/package.json
packages/data-store/package.json
packages/did-comm/package.json
packages/did-discovery/package.json
packages/did-jwt/package.json
packages/did-manager/package.json
packages/did-provider-ethr/package.json
packages/did-provider-ion/package.json
packages/did-provider-key/package.json
packages/did-provider-web/package.json
packages/did-resolver/package.json
packages/key-manager/package.json
packages/kms-local/package.json
packages/kms-web3/package.json
packages/message-handler/package.json
packages/remote-client/package.json
packages/remote-server/package.json
packages/selective-disclosure/package.json
packages/test-react-app/package.json
packages/test-utils/package.json
packages/url-handler/package.json
packages/utils/package.json
yarn.lock

Some dependencies were declared in the wrong section (devDeps instead of deps), causing them to be installed twice, possibly using different versions.
There is still a duplicate `@transmute/did-key-secp256k1` being imported with 2 different versions but that requires more refactoring.
this relates to #1044

chore(deps): deduplicate dependencies

---

packages/core/src/types/IDIDManager.ts
scripts/docs-build.ts

A newline in the inline documentation is causing the automatic deployment of the website to fail.
https://github.com/uport-project/veramo-website/actions/runs/3364937894/jobs/5579863804
This PR fixes the errant newline and also adds a patch to the documentation processing script to prevent this from repeating.

chore(build): fix newline in inline docs causing website build failures

---

__tests__/restAgent.test.ts
__tests__/shared/didCommAndDataStoreWithCredentials.ts
__tests__/shared/messageHandler.ts
packages/did-comm/src/message-handler.ts

fixes #944
DIDComm Message Handler should attempt to forward message to downstream handlers (but should not fail if none handle message)

fix: didcomm message handler should attempt to pass message to other handlers

---

packages/did-comm/src/__tests__/packing.test.ts
packages/utils/src/did-utils.ts

closes #1067 
Add support for `2020` key types in `extractPublicKeyHex` util function

fix(utils): correctly extract publicKeyHex from [Ed/X]25519 2020 keys

---

packages/credential-ld/src/ld-default-contexts.ts

Fixes issue where some files without `.json` suffix cannot be imported and throw `Can't resolve` error.
Adds `.json` to filenames that are missing it in `ld-default-contexts.ts`

fix(credential-ld): fix LDdefaultContexts file extensions

---

packages/core/plugin.schema.json
packages/core/src/types/IMessage.ts
packages/did-comm/plugin.schema.json
packages/did-comm/src/__tests__/message-handler.test.ts
packages/did-comm/src/message-handler.ts
packages/did-comm/src/types/message-types.ts
packages/message-handler/src/message.ts

closes #612
This adds support for `attachments` in DIDComm messages. The `DIDCommMessageHandler` will pass along the attachments after unpacking.

feat(did-comm) Support DIDComm Messaging attachments

---

packages/utils/src/__tests__/did-utils.test.ts
packages/utils/src/did-utils.ts

Potential missing of `verificationMethod.publicKeyJwk` in `getEthereumAddress()` Otherwise without this the method doesn't call `extractPublicKeyBytes()` that is able to manage this type of `VerificationMethod`.
Linking to an issue provides some context and a reason for the PR to be reviewed, as well as simplifying the release
notes and changelogs that get generated automatically. If an issue is linked like this it will be automatically closed
when the PR is merged.
A clear description of what this PR brings.

add publicKeyJwk as valid verificationMethod

---

.gitignore
packages/data-store-json/src/identifier/did-store.ts
packages/data-store-json/src/identifier/key-store.ts
packages/data-store-json/src/identifier/private-key-store.ts
packages/data-store/src/identifier/did-store.ts
packages/data-store/src/identifier/key-store.ts
packages/data-store/src/identifier/private-key-store.ts
packages/did-manager/src/abstract-identifier-store.ts
packages/did-manager/src/id-manager.ts
packages/did-manager/src/memory-did-store.ts
packages/key-manager/src/__tests__/abstract-key-store.test.ts
packages/key-manager/src/abstract-key-store.ts
packages/key-manager/src/abstract-private-key-store.ts
packages/key-manager/src/key-manager.ts
packages/key-manager/src/memory-key-store.ts
packages/kms-local/src/key-management-system.ts

fixes #1090
The `import` method name was causing issues on SES, so it was renamed in the DID/Key stores.
To keep the API consistent, I renamed all the other methods in the stores as well.
This is a BREAKING CHANGE, as the API of these interfaces is getting a rename.
Functionality remains the same.

fix: SES import method rename

---

packages/did-provider-pkh/package.json
pnpm-lock.yaml

fixes #1111
Adding missing `caip` dependency

fix: added missing caip dependency

---

packages/did-provider-pkh/src/pkh-did-provider.ts
packages/did-provider-pkh/src/resolver.ts

There's no issue being fixed, just small improvements on did-provider-pkh plugin:
- minor parameters corrections
- use of namespace parameter
- allow passing privateKey to import key directly on identifier creation
Only changing did-provider-pkh plugin. 

fix(did-provider-pkh): refactor and simplify did:pkh plugin

---

packages/did-provider-pkh/src/resolver.ts

fixes #1122 
Adds missing `.js` file extension for a relative path import.

fix: fixes missing `.js` file extension

---

packages/did-provider-ethr/src/index.ts
packages/did-provider-ethr/src/kms-eth-signer.ts

relates to #583
The `KMSEthereumSigner` class is now exported, but only for convenience.
It is not (yet) meant to be part of the public API.

fix(did-provider-ethr): export KMSEthereumSigner for convenience

---

packages/cli/src/config.ts
packages/cli/src/credential.ts
packages/cli/src/did.ts
packages/cli/src/discover.ts
packages/cli/src/execute.ts
packages/cli/src/explore/index.ts
packages/cli/src/lib/agentCreator.ts
packages/cli/src/message.ts
packages/cli/src/presentation.ts
packages/cli/src/sdr.ts
packages/cli/src/setup.ts
packages/core/package.json
pnpm-lock.yaml

Fixes #1125
- Adds a missing dependency to `@veramo/core`
- `@veramo/cli` awaits for agent creation from config file

Fix cli agent creation

---

packages/core-types/src/plugin.schema.json
packages/core-types/src/types/vc-data-model.ts
packages/credential-eip712/src/plugin.schema.json
packages/credential-ld/src/__tests__/issue-verify-flow.test.ts
packages/credential-ld/src/plugin.schema.json
packages/credential-ld/src/suites/JsonWebSignature2020.ts
packages/did-comm/src/plugin.schema.json
packages/selective-disclosure/src/plugin.schema.json
packages/utils/src/credential-utils.ts
packages/utils/src/type-utils.ts
scripts/prepare-integration-tests.ts

fixes #1073
This PR defines a data type for `@context` properties to include inline objects too, besides strings and string arrays.

feat(core-types): allow inline @context for Credentials and Presentations

---

jest.config.mjs
package.json
packages/cli/package.json
packages/cli/src/__tests__/cli.test.ts
packages/cli/src/__tests__/default.test.ts
packages/cli/src/cli.ts
packages/cli/src/config.ts
packages/cli/src/createCommand.ts
packages/cli/src/credential.ts
packages/cli/src/dev.ts
packages/cli/src/did.ts
packages/cli/src/discover.ts
packages/cli/src/execute.ts
packages/cli/src/explore/index.ts
packages/cli/src/lib/agentCreator.ts
packages/cli/src/lib/objectCreator.ts
packages/cli/src/message.ts
packages/cli/src/presentation.ts
packages/cli/src/sdr.ts
packages/cli/src/server.ts
packages/cli/src/version.ts
pnpm-lock.yaml

This PR refactors the way commander.js is used in the CLI package.
Instead of a global `program` command being mutated by different imports, each subcommand is created as an independent instance of a `Command` object.
The main purpose is to simplify testing, however due to incompatibilities between jest/ESM/chalk/typeorm the tests can't actually be performed using the same testing harness.
A custom jest config would be needed that must only be used on the CLI tests. When enabling the workaround in  https://github.com/facebook/jest/issues/12270#issuecomment-1111533936 any tests using typeorm in any way will fail.
This means we'd also need to only use JSON storage or memory storage configs in these CLI tests.
This PR also exports some of the methods used to configure the CLI through yaml. …

refactor(cli): use individual `Command` instances instead of global `program`

---

package.json
packages/cli/default/default.yml
packages/cli/package.json
packages/cli/src/__tests__/cli.test.ts
packages/cli/src/lib/agentCreator.ts
packages/cli/src/lib/objectCreator.ts
packages/cli/src/setup.ts
packages/cli/tsconfig.json
pnpm-lock.yaml

This adds support for did:pkh to the default CLI config.
```bash
> veramo did create
> veramo did resolve did:pkh:eip155.....
```
This also cleans some CLI initialization code and inline docs related to config loading.

feat(cli): add did:pkh support to the default CLI config

---

packages/cli/default/default.yml
packages/cli/package.json
pnpm-lock.yaml

This reverts commit 5887e048
The public gateway to the ceramic network was deprecated so we're removing support until did:3 v2 is launched or until we can find or host a more stable public gateway

Revert "feat(cli): add did:3 resolver to CLI default config (#1129)"

---

packages/did-comm/src/__tests__/trust-ping-interop.test.ts
packages/did-comm/src/utils.ts
packages/test-utils/src/example-did.ts
packages/test-utils/src/index.ts

https://github.com/decentralized-identity/didcomm-messaging/issues/435

chore: add DIDComm test using test vectors for recipient/sender

---

packages/data-store/src/entities/PreMigrationEntities.ts
packages/data-store/src/migrations/1.createDatabase.ts
packages/data-store/src/migrations/2.simplifyRelations.ts
packages/data-store/src/migrations/3.createPrivateKeyStorage.ts
packages/data-store/src/migrations/4.allowNullVPIssuanceDate.ts
packages/data-store/src/migrations/index.ts
packages/data-store/src/migrations/migration-functions.ts

In React-Native on older Android APIs (<11) the migrations where failing. That has to do with the 2nd and 3rd migration file. The 2nd migration file wasn't correctly creating new temp tables including privateKeyHex, because it picked up the wrong entity it seems. Probably because the matching logic on the metadata against a list of metadata has a different order in these environments.  As a result the 3rd migration also failed. It is now using a name when creating new tables, but using the actual matched table from the matching logic on existing tables.
Unrelated, the TypeORM migrations are failing in production settings where minifying is being used. That has to do with the fact that TypeORM relies on classnames and its timestamp suffix. When minifying this goes away, so I simply added …

Fix react-native migrations on older Android installations

---

packages/credential-ld/src/__tests__/issue-verify-ed25519-2020.test.ts
packages/credential-ld/src/ld-credential-module.ts
packages/credential-ld/src/ld-suites.ts
packages/credential-ld/src/suites/Ed25519Signature2020.ts
packages/utils/src/__tests__/did-utils.test.ts
packages/utils/src/did-utils.ts
pnpm-lock.yaml

This PR adds some code to handle some of the quirks of the Ed25519Signature2020 suite.
* There was a bug in the signature encoding. It was being interpreted as utf-8 instead of base64url !!
* The @context gets fixed before signing/verifying
* The VerificationMethod public key material is re-encoded as publicKeyMultibase
* The documentLoader was updated to support resolving DID document fragments as well. Since the document loader is only setup once for the whole plugin, this will end up failing all the other signature suite tests :(
This PR doesn't fix the suite, but perhaps someone can take over for the following days while I'm OOO.

some Ed25519Signature2020 fixes (still broken)

---

packages/cli/bin/veramo.js
packages/cli/default/default.yml
packages/cli/package.json
pnpm-lock.yaml

Allows agent configs to use did-provider-peer package (e.g. to add did-peer resolver)
- adds package to CLI dependencies
- adds did-peer resolver to default agent config
- Suppresses `ExperimentalWarning: Importing JSON modules` node warnings when running CLI

fix: add did-provider-peer to CLI dependencies

---

package.json
packages/cli/bin/veramo.js

Fixes #1163
I have not tested this on Windows, but [this comment](https://github.com/nodejs/node/issues/21960#issuecomment-1354555404) makes me think it should work.

fix(cli): NODE_NO_WARNINGS on windows

---

packages/credential-eip712/src/agent/CredentialEIP712.ts

Fixes issue where a credential in string format is encoded as a string twice. 
Removes JSON.stringify for string credential.

fix: remove JSON.stringify for string credential

---

packages/core/src/agent.ts
packages/did-comm/src/protocols/coordinate-mediation-message-handler.ts
packages/did-comm/src/protocols/index.ts

* Exports `@veramo/did-comm` mediator utility methods
* Changes debug message format in the `agent.execute` method to be more readable
old:
```
veramo:agent:resolveDid {didUrl: 'did:web:dev-didcomm-mediator.herokuapp.com'} 
veramo:agent:resolveDid:result {didDocumentMetadata: {…}, didResolutionMetadata: {…}, didDocument: {…}}
```
new:
```
veramo:agent:resolveDid arg {didUrl: 'did:web:dev-didcomm-mediator.herokuapp.com'} 
veramo:agent:resolveDid res {didDocumentMetadata: {…}, didResolutionMetadata: {…}, didDocument: {…}}
```

feat: exporting didcomm mediator utils

---

.github/workflows/build-and-test-on-pr.yml
.github/workflows/build-test-publish-on-push.yml
packages/cli/bin/veramo.js

This removes the warnings that appear when working with the CLI after the ESM upgrade

fix(cli): prevent `ExperimentalWarning` messages form being printed

---

packages/credential-w3c/src/action-handler.ts

Allows `Secp256r1` key type for verifiable credential and verifiable presentation creation.

feat: allow Secp256r1 key type

---

packages/utils/src/did-utils.ts

Adds support for publicKeyJwk and fixes issue 'key not found in document' when using `did:jwk`
Changes structure of if statement (makes it more readable) in `compareBlockchainAccountId` and adds `JsonWebKey2020` to said if statement.

fix: add support for publicKeyJwk

---

lerna.json

Lerna removed the `useWorkspaces` configuration and is failing builds that still have it. This PR removes that config, so that we get back release automation

chore(ci): update lerna.json workspaces

---

packages/did-resolver/src/universal-resolver.ts

According to the latest draft of the DID Resolution standard (v0.3); if the value of the Accept HTTP header is absent, the HTTP response body should be the DID document and not the DID resolution.
To get the DID resolution as response, you should send the header
Accept: application/ld+json;profile="https://w3id.org/did-resolution"
See https://w3c-ccg.github.io/did-resolution/#bindings-https
Universal Resolver does not follow this part of the standard and returns a DID resolution if the `Accept` header is omitted. To get a DID document, you must send the header
Accept: application/did+ld+json
By explicitly sending the `Accept` header, the `UniversalResolver` plugin can also be used for other services (like ours) that implement DID Resolution v0.3.
An `Accept` header is added with the value …

Send `Accept` header to universal resolver

---

packages/cli/src/explore/utils.ts
packages/credential-eip712/src/agent/CredentialEIP712.ts
packages/credential-ld/src/action-handler.ts
packages/credential-w3c/src/__tests__/action-handler.test.ts
packages/credential-w3c/src/action-handler.ts
packages/selective-disclosure/src/action-handler.ts
packages/utils/src/__tests__/credential-utils.test.ts
packages/utils/src/credential-utils.ts

Fixes #1201
```
{
credential: {
issuer: { id: `${identifier.did}?versionTime=${versionTime}` },
credentialSubject: {
id: 'did:web:example.com',
you: 'Rock',
},
},
proofFormat: 'jwt',
}
```
Remove DID parameters in the `issuer` and `holder` properties when looking up the identifier using the DID manager. The DID manager doesn't handle DID parameters like `versionTime`. When the DID manager is used we should be able to safely ignore them. They're only used when resolving the DID.
Added `options` property to `extractIssuer`, with option `removeParameters`. Added a `removeDIDParameters` function to credential-utils.
The `credentials-w3c`, `credentials-ld`, and `credentials-jwt` plugins all remove the DID parameters before looking up the identifier via the DID manager. If the DID is resolved, …

Allow DID parameters for verifiable credentials and presentations

---

__tests__/initial.migration.test.ts
__tests__/localAgent.test.ts
__tests__/localJsonStoreAgent.test.ts
__tests__/localMemoryStoreAgent.test.ts
__tests__/restAgent.test.ts
__tests__/shared/credentialStatus.ts
__tests__/shared/didManager.ts
__tests__/shared/documentationExamples.ts
__tests__/shared/handleSdrMessage.ts
__tests__/shared/keyManager.ts
__tests__/shared/utils.ts
__tests__/shared/verifiableDataEIP712.ts
__tests__/shared/webDidFlow.ts
packages/core-types/src/types/IResolver.ts
packages/credential-ld/src/ld-suite-loader.ts
packages/test-react-app/headless-tests/browserAgent.browser-test.ts
packages/test-react-app/src/App.tsx
packages/test-react-app/src/veramo/setup.ts

This is only a change in the tests to cover a wider range of scenarios by using different default DID providers between the integration test suites.
No functionality should be changed in this PR.

test: diversify default DID providers in tests to increase coverage

---

__tests__/shared/handleSdrMessage.ts
packages/core-types/src/plugin.schema.json
packages/core-types/src/types/IIdentifier.ts
packages/kms-local/src/key-management-system.ts
packages/selective-disclosure/src/action-handler.ts
packages/utils/src/__tests__/utils.test.ts
packages/utils/src/type-utils.ts

fixes #946
Added support for Ed25519 and Secp256r1 keys as signers of selective disclosure requests.

feat(selective-disclosure): support multiple key types for generating requests

---

__tests__/shared/saveClaims.ts
packages/data-store-json/src/data-store-json.ts
packages/data-store/src/data-store-orm.ts
packages/test-react-app/headless-tests/browserAgent.browser-test.ts
packages/test-react-app/src/veramo/setup.ts

There were 2 issues when running 
```typescript
await agent.dataStoreORMGetVerifiableCredentials({
order: [{ column: 'issuanceDate', direction: 'ASC' }],
take: 1,
skip: 1
})
```
- `data-store-orm.ts` was returning errors like `"credential" alias was not found. Maybe you forgot to join it?`
- `data-store-json.ts` was sorting in a wrong direction, and slicing result before sorting

fix(data-store): order skip take in orm and json

---

packages/data-store/src/data-store-orm.ts

When running `dataStoreORMGetVerifiableCredentials` with :
```
{
"order": [
{
"column": "issuanceDate",
"direction": "DESC"
}
],
"take": 10,
"skip": 0
}
```
on an agent that is using Postgres DB you would get this error: 
```
for SELECT DISTINCT, ORDER BY expressions must appear in select list
```
Using `qb.offset()` and `qb.limit()` instead of `qb.skip()` and `qb.take()`
As suggested here: https://github.com/typeorm/typeorm/issues/4742#issuecomment-783857414

fix(data-store): take and skip for postgres

---

packages/core-types/src/plugin.schema.json
packages/core-types/src/types/IDataStoreORM.ts

Adds another field to TCredentialColumns so it can be used in queries

feat: add hash to TCredentialColumns

---

packages/core-types/src/plugin.schema.json

schema generation on windows still puts in incorrect linebreaks. regenerate from macOS.

fix: regenerate schema

---

__tests__/shared/didManager.ts
__tests__/shared/webDidFlow.ts
packages/data-store-json/src/identifier/did-store.ts
packages/data-store/src/identifier/did-store.ts
packages/did-manager/src/abstract-identifier-store.ts
packages/did-manager/src/id-manager.ts
packages/did-manager/src/memory-did-store.ts

fixes #1215
* `DIDManager` no longer relies on the `alias`+`provider` pair when storing or filtering identifiers.
It is now impossible to use the same alias on 2 identifiers from different providers.
* Creating or importing an identifier using an alias that is already used will fail, no matter what provider is used.
* `didManagerGetOrCreate` still accepts a `provider` param in case it needs to create a new DID, but if it encounters an identifier with an existing `alias` but using a different `provider` it will throw an error.
* `AbstractDIDStore.getDID()` no longer uses a `provider` parameter.
* DID stores from `@veramo/data-store` and `@veramo/data-store-json` packages have been adapted to match the expected behavior of the DID manager
**BREAKING CHANGE**: The …

feat(did-manager): matching DIDs by alias should not depend on the provider

---

__tests__/utils/ganache-provider.ts

After bumping ethers to v6 the CI is manifesting some issues with tests that use ganache.
This PR adds a ganache provider that disables some of the ethersjs optimizations for caching and batching requests

test: fix ganache setup

---

__tests__/localJsonStoreAgent.test.ts
__tests__/shared/dbInitOptions.ts
packages/data-store/src/data-store.ts

fixes #1269
When deleting a credential, the corresponding claims are matched by the credential `hash` (internally computed) instead of the credential `id` which is optional.
I included the tests in the `localJsonStoreAgent` test suite as well to ensure similar behavior.
The `@veramo/data-store-json` did not manifest the same bug, but I added it to check for regressions.
This is a hotfix that should be release before the next major release

fix(data-store): match claims by credential hash when deleting credential

---

packages/data-store-json/src/data-store-json.ts

Some credentials from the wild are missing an `issuanceDate`, or have the date in a non-parseable format.
This fix defaults their date to unixtime(0) when compared to other credentials for database sorting.
I added #1274 to demonstrate how a test for this might look like, but it would introduce a breaking change (if people use their own migrations)

fix(data-store-json): order credentials with weird issuanceDate

---

packages/did-comm/src/__tests__/messagepickup-message-handler.test.ts
packages/did-comm/src/didcomm.ts
packages/did-comm/src/index.ts
packages/did-comm/src/plugin.schema.json
packages/did-comm/src/protocols/trust-ping-message-handler.ts
packages/did-comm/src/types/IDIDComm.ts

A return message will be included in the response to `sendDIDCommMessage` when `return_route: 'all'` is used in a packed message
```typescript
const messageId = v4()
const packedMessage = await agent.packDIDCommMessage({ 
message: {
type: 'example',
from: senderDid,
to: recipientDidUrl,
id: messageId,
body: {},
return_route: 'all'
},
packing: 'authcrypt'
})
const { returnMessage, transportId } = await agent.sendDIDCommMessage({ 
packedMessage, messageId, recipientDidUrl
})
console.log(returnMessage)
```

feat(did-comm): sendDIDCommMessage - returnMessage

---

packages/cli/src/mediate.ts
packages/did-comm/src/__tests__/coordinate-mediation-v3-message-handler.test.ts
packages/did-comm/src/__tests__/routing-message-handler-v3-coordinate-mediation.test.ts
packages/did-comm/src/__tests__/routing-message-handler.test.ts
packages/did-comm/src/protocols/coordinate-mediation-v3-message-handler.ts
packages/did-comm/src/protocols/index.ts
packages/did-comm/src/protocols/routing-message-handler.ts
packages/mediation-manager/README.md

This PR implements some minor refactoring and best practices with respect to the did-comm protocol (specifically coordinate mediation)
The PR:

QUICKFIX: Coordinate Mediation V3

---

packages/data-store/src/__tests__/data-store-orm.test.ts
packages/data-store/src/data-store-orm.ts

Signed-off-by: Mirko Mollik <mirko.mollik@fit.fraunhofer.de>
fixes #1285
It will reduce the credentials in case there were multiuple claims pointing to the claim credential

fix(data-store-orm): remove double entries

---

__tests__/localAgent.test.ts
__tests__/localJsonStoreAgent.test.ts
__tests__/localMemoryStoreAgent.test.ts
__tests__/restAgent.test.ts
__tests__/shared/didManager.ts
package.json
packages/did-provider-ethr/package.json
packages/did-provider-ion/package.json
packages/did-provider-key/package.json
packages/did-provider-pkh/package.json
packages/key-manager/package.json
packages/kms-local/package.json
packages/kms-web3/package.json
packages/test-react-app/src/veramo/setup.ts
packages/utils/package.json
pnpm-lock.yaml

n/a
This PR bumps the version of `ethr-did` in the `did-provider-ethr` to add support for `did:ethr:sepolia`. I am also bumping ethers across the board for compatibility with the new `ethr-did`. 
n/a

chore: upgrade ethers and did-provider-ethr for sepolia support

---

packages/cli/src/dev.ts

Example:
fixes #1317
Adding a new parameter to the cli so the path and file of the `plugin.schema.json`.

[proposal] make path output from generate schema dynamic

---

packages/core-types/src/plugin.schema.ts
packages/did-comm/src/plugin.schema.ts

This is preventing the CI/CD script to publish the snapshots from `next`

chore: fix typo in plugin schemas

---

packages/selective-disclosure/src/action-handler.ts
packages/selective-disclosure/src/message-handler.ts

Based on the discussion in https://github.com/decentralized-identity/veramo/issues/1276#issuecomment-1857576346 , the uPort-era-selective-disclosure-plugin should be marked as deprecated to be removed in a future release.

fix(selective-disclosure): deprecate the uPort SelectiveDisclosure plugin

---

__tests__/shared/verifiableDataLD.ts
packages/credential-ld/src/ld-credential-module.ts
packages/credential-ld/src/ld-suite-loader.ts
packages/credential-ld/src/ld-suites.ts
packages/credential-ld/src/suites/EcdsaSecp256k1RecoverySignature2020.ts
packages/credential-ld/src/suites/Ed25519Signature2018.ts
packages/credential-ld/src/suites/Ed25519Signature2020.ts
packages/credential-ld/src/suites/JsonWebSignature2020.ts

fixes #1329
The `VeramoLdSignature.getSupportedVerificationType()` can now return `string[]` as well as `string`
This allows `VeramoLdSignature` suite implementations to signal compatibility with multiple Verification Method types for verification.

fix(credential-ld): let verifiers use all supported verification methods

---

__tests__/shared/verifiableDataLD.ts
packages/credential-eip712/src/agent/CredentialEIP712.ts
packages/credential-ld/src/ld-credential-module.ts
packages/credential-ld/src/ld-suite-loader.ts
packages/credential-ld/src/ld-suites.ts
packages/credential-ld/src/suites/EcdsaSecp256k1RecoverySignature2020.ts
packages/credential-ld/src/suites/Ed25519Signature2018.ts
packages/credential-ld/src/suites/Ed25519Signature2020.ts
packages/credential-ld/src/suites/JsonWebSignature2020.ts
packages/credential-status/package.json
packages/did-discovery/src/action-handler.ts
packages/did-provider-key/package.json
packages/did-provider-key/src/__tests__/key.resolver.test.ts
packages/did-provider-key/src/resolver.ts
packages/did-provider-peer/src/resolver.ts
packages/mediation-manager/src/mediation-manager.ts
pnpm-lock.yaml

fixes #1330
The did:key resolver implementations imported from transmute resolved to outdated Verification method formats.
This PR replaces those dependencies with a local implementation that also adheres better to the spec for defaults and behavior.
The verification methods default to `JsonWebKey2020`, unless otherwise specified through the `options.publicKeyFormat` parameter.
This implementation also supports `options.enableEncryptionKeyDerivation`, defaulting to `true`, that triggers the expression of the corresponding X25519 `keyAgreement` key for an Ed25519 public key.
This implementation supports `Ed25519`, `X25519`, `Secp256k1`, and `P-256` key types for did:key.
This PR is based on #1331, as changing the default verification methods in did:key triggers the …

fix(did-provider-key): align did:key resolver to spec

---

__tests__/shared/utils.ts
packages/credential-eip712/src/agent/CredentialEIP712.ts
packages/utils/src/__tests__/did-utils.test.ts
packages/utils/src/did-utils.ts

Getting correct chainId for any did method

fix(credential-eip712): chainId for any did method

---

__tests__/localAgent.test.ts
__tests__/localJsonStoreAgent.test.ts
__tests__/restAgent.test.ts
__tests__/shared/verifiableDataLD.ts
packages/core-types/src/plugin.schema.ts
packages/core-types/src/types/ICredentialIssuer.ts
packages/core-types/src/types/ICredentialStatusVerifier.ts
packages/core-types/src/types/ICredentialVerifier.ts
packages/credential-eip712/src/agent/CredentialEIP712.ts
packages/credential-eip712/src/plugin.schema.ts
packages/credential-eip712/src/types/ICredentialEIP712.ts
packages/credential-ld/src/action-handler.ts
packages/credential-ld/src/ld-credential-module.ts
packages/credential-ld/src/plugin.schema.ts
packages/credential-ld/src/types.ts
packages/credential-status/src/credential-status.ts
packages/credential-w3c/src/action-handler.ts
packages/did-comm/src/didcomm.ts
packages/did-comm/src/plugin.schema.ts
packages/did-comm/src/types/IDIDComm.ts
packages/did-comm/src/utils.ts
packages/test-react-app/src/veramo/setup.ts
packages/utils/src/did-utils.ts

fixes #1343
Plugin methods that rely on did-resolver can now accept an optional `resolutionOptions` parameter that gets forwarded to the DID resolver.
Affected packages:
`@veramo/credential-w3c`
`@veramo/credential-ld`
`@veramo/credential-eip712`
`@veramo/did-comm`

fix(credential-w3c): forward DID resolution options to the resolver

---

packages/cli/default/default.yml
packages/cli/src/credential.ts

fixes #1342
The `veramo credential create` command would ask if the credential being created should be revokable but would then use an incompletely supported credentialStatus method, making the credentials unverifiable (using default configs).
Since the command is (still) meant as a simple demo, it's easier to simply remove that option.
Additionally, the credential is now getting saved using data-store API instead of the deprecated `save` option and the verification is a bit more lenient with JSON5 inputs.

fix(cli): remove `revocable` and `send` options from credential create command

---

package.json
packages/cli/package.json
packages/cli/src/execute.ts
packages/cli/src/imported-types/imported-modules.d.ts
packages/credential-w3c/src/action-handler.ts
pnpm-lock.yaml

fixes #1281
When calling `veramo execute` without parameters, the CLI will no longer offer a list of available methods based on `oas-resolver`.
Also, the `execute` command is now using `Debug` instead of `console.log` for logging, so that the console can be used for stdout and piping. Example: `veramo execute -m didManagerFind -a '{}' | jq '.[0].did'` to get the DID of the first identifier managed locally.
The discussion in #1281 lead to the decision to remove this functionality from the CLI

fix(cli): remove interactive prompting on CLI execute command

---

__tests__/mediation.test.ts
packages/core/src/agent.ts
packages/did-comm/src/__tests__/coordinate-mediation-v3-message-handler.test.ts
packages/did-comm/src/protocols/coordinate-mediation-v3-message-handler.ts
packages/did-comm/src/protocols/routing-message-handler.ts
packages/did-comm/src/protocols/trust-ping-message-handler.ts
packages/did-comm/src/transports/transports.ts
packages/remote-server/src/messaging-router.ts

This adds a test that shows how to use the did-comm mediation features.
The mediation flow is quite cumbersome and strict. Proposals welcome for improving the state of things.

test: add a test as an example of using did-comm mediation

---

packages/did-resolver/src/__tests__/resolver.test.ts
packages/did-resolver/src/resolver.ts

`fixes #1364`
The `getDIDComponentById` function in `did-resolver/src/resolver.ts` is modified so that it correctly finds the result when the `didUrl` passed in is a keyID without the DID prefixed to it, but the resolved DID Document lists the key with the prefix.
it's possible that this is not the ideal solution and the proper fix for the bug is upstream from this function

fix: address edge case when getting DIDDoc component

---

packages/core-types/src/types/ICredentialIssuer.ts
packages/credential-w3c/src/action-handler.ts

This PR extends the credential-w3c actionHandler logic by adding support for bbs signatures.
In this way, it will be possible to generate plugins that implement the creation of Verifiable Credentials and Verifiable Presentations, as well as their verification using bbs-type signatures.
According to what was discussed here:
[https://discord.com/channels/878293684620234752/1220477267172659360/1227352488579961003](https://discord.com/channels/878293684620234752/1220477267172659360/1227352488579961003)
These changes only extend the logic of the action-handler, they do not include the implementation of the plugin.

feat(credential-w3c): added support bbs proof format

---

packages/did-provider-ethr/src/__tests__/ethr-did-provider.test.ts
packages/did-provider-ethr/src/ethr-did-provider.ts

Closes #1373 
Due to constraints within the secure MetaMask Snap context, it is not possible to invoke the `didManagerAdd(Remove)Service` or `didManagerAdd(Remove)Key` methods on the `did-manager` successfully. Refer [here](https://github.com/MetaMask/snaps/issues/2158) for the list of blocked RPC methods. 
As outlined in the referenced issue, the changes proposed herein allow for the transaction to be signed only, through the addition of a new `signOnly` flag within one agent (in the demonstration case, by an agent in the constrained MetaMask Snap environment), and then submitted from another context (for example via the `ethers.InfuraProvider` in another context). 
I have successfully tested this (with the `did-ethr-provider` on the `sepolia` testnet).

feat: add signOnly flag and logic for add/remove key/service

---

packages/data-store/src/data-store.ts
packages/data-store/src/identifier/did-store.ts

This PR addresses a performance issue with TypeORM (https://github.com/typeorm/typeorm/issues/5694) 
When using `findOne()` with attached relations, TypeORM executes two queries:
```
query: SELECT DISTINCT "distinctAlias"."Identifier_did" AS "ids_Identifier_did" FROM (SELECT "Identifier"."did" AS "Identifier_did", "Identifier"."provider" AS "Identifier_provider", "Identifier"."alias" AS "Identifier_alias", "Identifier"."controllerKeyId" AS "Identifier_controllerKeyId", "Identifier__Identifier_keys"."kid" AS "Identifier__Identifier_keys_kid", "Identifier__Identifier_keys"."kms" AS "Identifier__Identifier_keys_kms", "Identifier__Identifier_keys"."type" AS "Identifier__Identifier_keys_type", "Identifier__Identifier_keys"."publicKeyHex" AS "Identifier__Identifier_keys_publicKeyHex", …
```

perf: replace TypeOrm `findOne` queries including relations with `find`

---

packages/did-resolver/src/__tests__/integration.test.ts

* remove integration tests that attempt to resolve did:web:did.actor:alice as the service is no longer operational
Example:
`fixes #1413`
tests are simply commented out until a suitable replacement is found

chore(did-resolver): remove integration tests that rely on non-operational service

---

packages/core-types/src/plugin.schema.ts

* npm publish failing due to out of date `plugin.schema.ts` in `core-types` after recent dependency update

fix(core-types): regenerate plugin schema

---

package.json
packages/cli/package.json
packages/did-provider-ethr/package.json
packages/did-resolver/package.json
packages/test-react-app/package.json
pnpm-lock.yaml

ethr-did-resolver@<11.x package was causing some bundlers to fail in certain situations due to a missing default export.

fix(deps): bump ethr-did-resolver to v11

---

packages/credential-status/src/credential-status.ts

`credential-status` plugin is missing a schema definition, causing it to crash the OpenAPI schema generator in `@veramo/remote-client`, so fails with remote agents.
Added schema

fix(credential-status): plugin class missing OpenAPI schema

---

packages/core-types/src/plugin.schema.ts
packages/core-types/src/types/IKeyManager.ts
packages/key-manager/src/key-manager.ts

Closes #1353
Add support for a user defined `kid` on `keyManagerCreate`

feat(key-manager): allow user defined kid on keyManagerCreate

---

packages/did-provider-ethr/package.json
packages/did-provider-ethr/src/__tests__/ethr-did-provider.test.ts
packages/did-provider-ethr/src/ethr-did-provider.ts
packages/did-provider-ethr/tsconfig.json
packages/did-provider-jwk/src/__tests__/jwk.test.ts
packages/did-provider-jwk/src/jwk-did-provider.ts
packages/did-provider-jwk/src/types/jwk-provider-types.ts
packages/did-provider-key/__tests__/key-did-provider.test.ts
packages/did-provider-key/src/key-did-provider.ts
packages/did-provider-peer/src/peer-did-provider.ts
packages/did-provider-pkh/package.json
packages/did-provider-pkh/src/pkh-did-provider.ts
packages/did-provider-pkh/tsconfig.json
packages/did-provider-web/package.json
packages/did-provider-web/src/web-did-provider.ts
packages/did-provider-web/tsconfig.json
packages/utils/src/did-utils.ts
packages/utils/src/types/utility-types.ts
pnpm-lock.yaml

At the moment, specifying key options when creating identifiers (via `didManagerCreate`) is fragile. Each provider has a slightly different format for `options`, and many omit the ability to provide `meta` for keys. This is a problem, as it means there is no nice way to create both an identifier and associated keys if you need to store metadata.
This PR proposes some non-breaking changes to each of the DID providers that unifies key option signature with a base type. It passes all key options from `options.key` to `keyManagerCreate/keyManagerImport` automatically.
If no `options.key` or `options.keyRef` is provided, each provider falls back to the currently support configuration signature, which has been deprecated.
`createIdentifier` methods on each DID provider now utilise a base …

feat: improve key creation/import options when creating identifiers

---

packages/credential-w3c/src/action-handler.ts

Based on a discussion on Discord, this PR removes an obsolete "didManagerGet" in the credential-w3c plugin within the createVerifiablePresentation function, because the specific code is additionally checked in the specific credential plugin which is called afterwards. This reduces the SQL query amount of the function.
Remove the unused code in the action-handler of the credential-w3c plugin.

perf: remove unused didManagerGet in createVerifiablePresentation

---

.github/workflows/build-and-test-on-pr.yml
.github/workflows/sync-next-with-latest.yml

https://github.com/decentralized-identity/veramo/security/code-scanning/5
https://github.com/decentralized-identity/veramo/security/code-scanning/19
https://github.com/decentralized-identity/veramo/security/code-scanning/20
https://github.com/decentralized-identity/veramo/security/code-scanning/21
https://github.com/decentralized-identity/veramo/security/code-scanning/22
https://github.com/decentralized-identity/veramo/security/code-scanning/23
Explicitly sets the permissions on GH workflows

chore(ci): limit GH workflow permissions
